# Generated by Django 3.2.6 on 2021-08-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadodelTicket', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('estatus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DjangoTicketApp.estado')),
                ('idHistoriaUsuario', models.ForeignKey(help_text='la historia de usuario es', on_delete=django.db.models.deletion.CASCADE, to='DjangoTicketApp.historiausuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('empresaAsociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoTicketApp.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='idProyectoDesarrollo',
            field=models.ForeignKey(help_text='Proyecto al que pertenece', on_delete=django.db.models.deletion.CASCADE, to='DjangoTicketApp.proyectodesarrollo'),
        ),
    ]
